server {
    listen 80;
    listen [::]:80;
    server_name chinese.ztvmm.live;
    location ^~ /.well-known/acme-challenge/ { root /var/www/html; default_type text/plain; }
    location / { return 503; }
}
